---
# defaults file for ansible-custom-tor
custom_tor_dirname: "tor" # Directory name of the Tor sources
custom_tor_src_dirpath: "." # Directory in the local machine where the custom Tor sources are
custom_tor_dest_dirpath: "{{ ansible_env.HOME }}" # Absolute path to the directory from the target machine where the custom Tor sources will be placed
