language: python
python:
  - "2.7"
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - sudo apt-get -qq install xvfb tcpdump wireshark Xvfb
before_script:
  - cd test
script:  py.test
