---
- stat: path="{{ custom_tor_dest_dir }}/autogen.sh"
  register: autogen_sh

- name: Autogen custom Tor if autogen.sh exists (i.e. git clone).
  command: ./autogen.sh
  args:
    chdir: "{{ custom_tor_dest_dir }}"
  when: autogen_sh.stat.exists

- name: Configure custom Tor.
  command:
    ./configure --disable-asciidoc
  args:
    chdir: "{{ custom_tor_dest_dir }}"
    creates: "{{ custom_tor_dest_dir }}/Makefile"

- name: Make custom Tor
  make:
    chdir: "{{ custom_tor_dest_dir }}"
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"

- name: Install custom Tor
  make:
    target: install
    chdir: "{{ custom_tor_dest_dir }}"
  become: yes
