---
# tasks file for ansible-swapon
- block:
    - shell: "umount /dev/xvdb"
    - shell: "mkswap /dev/xvdb"
    - shell: "swapon /dev/xvdb"
    - shell: "free -m"
      register: free_cmd
    - debug: msg={{ free_cmd.stdout }}

    # - name: Create swap file.
    #   command:
    #     fallocate -l {{ memory_amount }} {{ swap_file_path }}
    #   when: ansible_swaptotal_mb < 1
    #   register: swapfile_created

    # - name: Set swapfile permissions.
    #   file:
    #     path="{{ swap_file_path }}"
    #     mode={{ swap_file_mode }}
    #   when: swapfile_created.changed

    # - name: Format swapfile as swap.
    #   command: mkswap "{{ swap_file_path }}"
    #   when: swapfile_created.changed

    # - name: Add swap to fstab.
    #   mount:
    #     name=swapfile
    #     src={{ swap_file_path }}
    #     fstype={{ mount_fstype }}
    #     opts=sw
    #     passno=0
    #     dump=0
    #     state=present
    #   when: swapfile_created.changed

    # - name: Enable swap.
    #   command: swapon "{{ swap_file_path }}"
    #   when: swapfile_created.changed
  become: yes
  ignore_errors: true
